export const GET_CHECK_INS_PENDING = 'GET_CHECK_INS_PENDING'
export const GET_CHECK_INS_SUCCESS = 'GET_CHECK_INS_SUCCESS'
export const GET_CHECK_INS_FAILED = 'GET_CHECK_INS_FAILED'

export const GET_ONE_CHECK_IN_PENDING = 'GET_ONE_CHECK_IN_PENDING'
export const GET_ONE_CHECK_IN_SUCCESS = 'GET_ONE_CHECK_IN_SUCCESS'
export const GET_ONE_CHECK_IN_FAILED = 'GET_ONE_CHECK_IN_FAILED'

export const ADD_CHECK_IN_PENDING = 'ADD_CHECK_IN_PENDING'
export const ADD_CHECK_IN_SUCCESS = 'ADD_CHECK_IN_SUCCESS'
export const ADD_CHECK_IN_FAILED = 'ADD_CHECK_IN_FAILED'

export const EDIT_CHECK_IN_PENDING = 'EDIT_CHECK_IN_PENDING'
export const EDIT_CHECK_IN_SUCCESS = 'EDIT_CHECK_IN_SUCCESS'
export const EDIT_CHECK_IN_FAILED = 'EDIT_CHECK_IN_FAILED'

export const DELETE_CHECK_IN_PENDING = 'DELETE_CHECK_IN_PENDING'
export const DELETE_CHECK_IN_SUCCESS = 'DELETE_CHECK_IN_SUCCESS'
export const DELETE_CHECK_IN_FAILED = 'DELETE_CHECK_IN_FAILED'